repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: double-quote-string-fixer
      - id: check-toml
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/dosisod/refurb
    rev: v1.27.0
    hooks:
      - id: refurb
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: ['--unsafe-fixes']
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

default_language_version:
  python: python3.11
