# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: BeePy
site_url: https://kor0p.github.com/BeePy

repo_name: kor0p/BeePy
repo_url: https://github.com/kor0p/BeePy

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
#    - navigation.tabs  # Header tabs, for future
    - navigation.sections
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: lime
  icon:
    annotation: material/plus-circle-outline

extra_css:
  - stylesheets/extra.css

extra:
#  version:  # Turn on when it will be useful
#    provider: mike
#    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kor0p/BeePy
    - icon: fontawesome/brands/telegram
      link: https://t.me/kor0p
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kor0p/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # new
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2022 - 2024 <a href="https://github.com/kor0p" target="_blank" rel="noopener">Viktor Koropetskyi 🇺🇦</a>

# Page tree
nav:
  - Welcome: index.md
  - Examples: live-examples.md
  - Local development: local-development-guide.md
