[[redirects]]
  from = "/"
  to = "https://pyweb.herokuapp.com/e/list-examples"

[[redirects]]
  from = "/examples"
  to = "https://pyweb.herokuapp.com/e/list-examples"

[[redirects]]
  from = "/examples/*"
  to = "https://pyweb.herokuapp.com/e/:splat"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"