[[redirects]]
  from = "/"
  to = "https://beepy.herokuapp.com/e/"

[[redirects]]
  from = "/examples"
  to = "https://beepy.herokuapp.com/e/"

[[redirects]]
  from = "/examples/*"
  to = "https://beepy.herokuapp.com/e/:splat"

[[redirects]]
  from = "/beepy.js"
  to = "https://kor0p.github.io/BeePy/beepy.js"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"