[[redirects]]
  from = "/"
  to = "https://pyweb.herokuapp.com/e/"

[[redirects]]
  from = "/examples"
  to = "https://pyweb.herokuapp.com/e/"

[[redirects]]
  from = "/examples/*"
  to = "https://pyweb.herokuapp.com/e/:splat"

[[redirects]]
  from = "/pyweb.js"
  to = "https://kor0p.github.io/PyWeb/pyweb.js"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"